### ISSUE TITLE
Fallback container

### ISSUE THREAD

**Issue by pbenedict** [kintesh/containerise#78] opened 2019-07-29 16:55 UTC
I have a couple rules dedicated to domains. However, I am in need of a fallback container that is used when no rules match.

I attempted it. First, I created a named "Default" container. Second, I specified `*` to match everything else, and placed it last. My hope was that specific matches take precedence, and process first, over more generic matches.

I specified this:
`*.google.com , Google`
`*.microsoft.com , Microsoft`
`* , Default`

Saving sorted to this:
`* , Default`
`*.google.com , Google`
`*.microsoft.com , Microsoft`

So it resulted in every page opening in the "Default" container. It seems, therefore, the only ordering is alphabetical as of version 3.2.0. 

In my opinion, the improvement with least coding effort would be to consider `*` the most generic match, always sorting it as such, and placing it last. This seems sensible and logical. My need, also, would be immediately fulfilled.

WDYT?

**Comment by LoveIsGrief** [comment] 2019-07-30 07:59
Duplicate of #10 . I invite you to copy that comment there.

**Closed by LoveIsGrief** 2019-07-30 07:59 UTC
