### ISSUE TITLE
Open unmatched URL in default container doesn't work with local html files

### ISSUE THREAD

**Issue by Nepherte** [kintesh/containerise#103] opened 2019-10-10 03:12 UTC
When enabling the setting "open unmatched URL in a default container", I am no longer able to open html files locally available on my machine (ie. file:///path/to/my/file.html).

It initially opens up in Firefox in No Container, subsequently closes the tab (expected), but doesn't open the file in a new tab within the configured default container.

**Comment by LoveIsGrief** [comment] 2019-10-10 14:03
Thanks for the bug report. Was able to reproduce this with default containers as well as older versions that matched `file://` URLs.

[`tabs.create`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/create) simply doesn't support those type of URLs. 

They'll simply have to be ignored.

**Comment by Nepherte** [comment] 2019-10-10 14:08
In my case, I dont want to bind them to a specific container so I don't mind them being in "No Container"

**Comment by LoveIsGrief** [comment] 2019-10-10 14:13
We can't reassign / reopen tabs with `file://` URLs at all due to the webextension API refusing to do that. The PR will exclude such URLs completely from treatment. Unfortunately, the user will have to do the work of reopening the tab in the wished container themselves

**Comment by Nepherte** [comment] 2019-10-10 14:14
That's an acceptable solution. No worries.

**Closed** 2019-10-11 21:08 UTC
Labels: bug
